from __future__ import annotations

import hashlib
import json
from collections import Counter
from pathlib import Path


DATA_DIR = Path(__file__).resolve().parents[1] / "src" / "diet_bot" / "data"

PROTECTED_RECOVERY_FOOD_IDS = frozenset(
    {
        "chicken_liver",
        "cod_liver_canned_drained",
        "herring",
        "sardines",
        "sprats",
    }
)

LATE_928_LATE_SOURCE_FOOD_IDS = frozenset(
    {
        "adyghe_cheese",
        "edamame",
        "lentils_dry",
        "rice_paper",
        "tempeh",
        "textured_soy_protein_dry",
    }
)

LATE_928_HISTORICAL_FOOD_IDS = frozenset(
    {
        "cooked_rice",
        "cream_10_percent",
        "cream_20_percent",
        "lean_beef_ground",
    }
)

LATE_928_RECONCILED_FOOD_IDS = LATE_928_LATE_SOURCE_FOOD_IDS | LATE_928_HISTORICAL_FOOD_IDS
LATE_928_UNUSED_LATE_FOOD_IDS = frozenset({"american_cheese", "harissa"})
RECOVERY_BASE_FOOD_ROW_COUNT = 359
RECOVERY_BASE_FOOD_ROWS_SHA256 = "b397af8529604859ab65fd70145f2c6f214dec003a43b0a04939a5ee1808ef8a"

EXPECTED_RECONCILED_FOOD_SOURCES = {
    "adyghe_cheese": ("", "Estimated from common retail Adyghe cheese labels; conservative sodium bounded for bulk import."),
    "cooked_rice": ("168878", "Rice, white, long-grain, regular, enriched, cooked"),
    "cream_10_percent": ("171255", "Cream, fluid, half and half"),
    "cream_20_percent": ("170857", "Cream, fluid, light (coffee cream or table cream)"),
    "edamame": ("168410", "Edamame, frozen, unprepared"),
    "lean_beef_ground": ("171796", "Beef, ground, 85% lean meat / 15% fat, raw"),
    "lentils_dry": ("2644283", "Lentils, dry"),
    "rice_paper": ("2708166", "Rice paper"),
    "tempeh": ("174272", "Tempeh"),
    "textured_soy_protein_dry": ("2707451", "Textured vegetable protein, dry"),
}

PLANNED_LATE_928_INGREDIENT_FOOD_IDS = frozenset(
    {
        "acai_puree",
        "adyghe_cheese",
        "agave_syrup",
        "aioli",
        "allspice",
        "almond_butter",
        "almond_milk",
        "almonds",
        "anchovies",
        "apple",
        "apple_juice",
        "apple_sauce",
        "artichoke",
        "arugula",
        "asparagus",
        "avocado",
        "bacon",
        "bagel",
        "baguette",
        "baking_powder",
        "baking_soda",
        "balsamic_glaze",
        "banana",
        "barbecue_sauce",
        "basil",
        "bay_leaf",
        "beef_broth",
        "beef_chuck",
        "beef_ground",
        "beef_sirloin",
        "beef_stew",
        "beer",
        "beet",
        "bell_pepper",
        "berries",
        "black_bean_sauce",
        "black_beans",
        "black_pepper",
        "blackberries",
        "blueberries",
        "bok_choy",
        "bran_flakes",
        "brazil_nuts",
        "breadcrumbs",
        "broccoli",
        "broth_cube",
        "brown_sugar",
        "brussels_sprouts",
        "buckwheat",
        "bulgur",
        "burger_bun",
        "butter",
        "buttermilk",
        "butternut_squash",
        "buttery_crackers",
        "cabbage",
        "cajun_seasoning",
        "calamari",
        "canola_oil",
        "capers",
        "cardamom",
        "carrot",
        "carrot_ginger_dressing",
        "cashews",
        "cauliflower",
        "cayenne",
        "celeriac",
        "celery",
        "cereal_flakes",
        "cheddar",
        "cherries",
        "chia_seeds",
        "chicken_breast",
        "chicken_broth",
        "chicken_drumstick",
        "chicken_ground",
        "chicken_liver",
        "chicken_thigh",
        "chicken_thigh_skinless",
        "chickpeas",
        "chili_flakes",
        "chili_oil",
        "chili_pepper",
        "chili_powder",
        "chipotle_mayo",
        "chorizo",
        "ciabatta",
        "cilantro",
        "cinnamon",
        "cinnamon_stick",
        "clam_stock",
        "clams",
        "cloves",
        "cocoa_powder",
        "coconut_flakes",
        "coconut_milk",
        "coconut_oil",
        "cod_fillet",
        "cod_liver_canned_drained",
        "coffee_brewed",
        "cooked_rice",
        "coriander",
        "corn",
        "corn_cob",
        "corn_kernels",
        "corn_tortilla",
        "corn_tortilla_extra",
        "cornichons",
        "cornmeal",
        "cornstarch",
        "cottage_cheese",
        "couscous",
        "crab_sticks",
        "crackers",
        "cranberries_dried",
        "cranberry_sauce",
        "cream",
        "cream_10_percent",
        "cream_20_percent",
        "cream_cheese",
        "creme_fraiche",
        "cucumber",
        "cumin",
        "curry_leaves",
        "curry_powder",
        "dark_chocolate",
        "dates",
        "dill",
        "dried_apricots",
        "edamame",
        "egg",
        "egg_noodles",
        "egg_white",
        "egg_white_extra",
        "egg_yolk",
        "eggplant",
        "english_muffin",
        "falafel_prepared",
        "fava_beans",
        "fava_young",
        "fennel_bulb",
        "fennel_seed",
        "feta",
        "fig",
        "fish_sauce",
        "fish_stock",
        "five_spice",
        "flaxseed_ground",
        "flour_tortilla",
        "garam_masala",
        "garlic",
        "garlic_croutons",
        "garlic_powder",
        "gelatin",
        "ginger",
        "gnocchi",
        "goat_cheese",
        "gouda",
        "granola",
        "grapefruit",
        "grapes",
        "greek_yogurt",
        "green_beans",
        "green_onion",
        "green_peas",
        "greens",
        "grilled_vegetables",
        "ground_meat",
        "guacamole",
        "ham",
        "hemp_seeds",
        "herring",
        "honey",
        "horseradish",
        "hot_sauce",
        "hummus",
        "ice",
        "italian_sausage",
        "italian_seasoning",
        "kale",
        "kefir",
        "ketchup",
        "kiwi",
        "kombu",
        "korean_carrot",
        "ladyfingers",
        "lamb_ground",
        "lavash",
        "lean_beef_ground",
        "leek",
        "lemon_juice",
        "lemongrass",
        "lentils",
        "lentils_dry",
        "lettuce",
        "lime_juice",
        "mackerel",
        "mandarin",
        "mango",
        "maple_syrup",
        "marinara",
        "mascarpone",
        "mayonnaise",
        "microgreens",
        "milk",
        "mini_chocolate_chips",
        "mint",
        "miso_paste",
        "mixed_nuts",
        "mixed_spices",
        "molasses",
        "monterey_jack",
        "mozzarella",
        "muesli",
        "mung_sprouts",
        "mushrooms",
        "mussels",
        "mustard",
        "mustard_seed",
        "napa_cabbage",
        "nori",
        "nutmeg",
        "nuts_mix",
        "oat_cookie",
        "oat_groats",
        "oats",
        "olive_oil",
        "olive_oil_spray",
        "olives",
        "onion",
        "onion_powder",
        "orange",
        "oregano",
        "orzo",
        "oyster_sauce",
        "paprika",
        "parmesan",
        "parsley",
        "parsnip",
        "passata",
        "passion_fruit",
        "pasta_generic",
        "peach",
        "peanut_butter",
        "peanut_oil",
        "peanuts",
        "pear",
        "pear_ripe",
        "pearl_barley",
        "pecans",
        "pecorino",
        "pepperoncini",
        "pesto",
        "pickle_brine",
        "pickles",
        "pine_nuts",
        "pineapple",
        "pistachios",
        "pita",
        "pita_extra",
        "pomegranate",
        "poppy_seed",
        "pork_chop",
        "pork_loin",
        "pork_tenderloin",
        "potato",
        "pretzels",
        "processed_cheese",
        "prosciutto",
        "pumpkin",
        "pumpkin_puree",
        "pumpkin_seeds",
        "quinoa",
        "radish",
        "raisins",
        "ranch",
        "ranch_seasoning",
        "raspberries",
        "red_beans",
        "red_cabbage",
        "red_pepper_flakes",
        "rice",
        "rice_flour",
        "rice_noodles",
        "rice_paper",
        "ricotta",
        "roasted_pepper",
        "roasted_red_pepper",
        "root_vegetables",
        "rosemary",
        "rye_flour",
        "saffron",
        "sage",
        "salmon",
        "salsa",
        "salt",
        "sambal_olek",
        "sardines",
        "sausage",
        "scallops",
        "seafood_mix",
        "semolina",
        "sesame_oil",
        "sesame_seeds",
        "shiitake",
        "shishito_pepper",
        "shrimp",
        "sichuan_pepper",
        "smoked_white_fish",
        "soba_noodles",
        "sour_cream",
        "soy_sauce",
        "spaghetti",
        "spelt",
        "spinach",
        "split_peas",
        "sprats",
        "sriracha",
        "sriracha_extra",
        "star_anise",
        "stir_fry_vegetables",
        "strawberries",
        "sugar",
        "sunflower_seeds",
        "sunflower_seeds_salted",
        "sweet_potato",
        "swiss_cheese",
        "tahini",
        "tamari",
        "tarragon",
        "tempeh",
        "teriyaki_sauce",
        "textured_soy_protein_dry",
        "thai_curry_paste",
        "thin_flatbread",
        "thyme",
        "tofu",
        "tomato",
        "tomato_paste",
        "tomato_puree",
        "trout",
        "tuna",
        "tuna_steak",
        "turkey",
        "turkey_ground",
        "turkey_or_chicken_breast",
        "turmeric",
        "tzatziki",
        "udon_noodles",
        "vanilla_extract",
        "vegetable_broth",
        "vegetable_oil",
        "vegetable_toppings",
        "vinegar",
        "walnuts",
        "water",
        "watermelon",
        "wensleydale_cheese",
        "wheat_flour",
        "wheat_germ",
        "whey_protein",
        "white_fish",
        "white_pepper",
        "whole_grain_bread",
        "whole_wheat_pasta",
        "wine",
        "worcestershire",
        "yeast",
        "zucchini",
    }
)


def test_curated_food_ids_are_unique() -> None:
    rows = _curated_food_rows()
    duplicates = sorted(food_id for food_id, count in Counter(row["food_id"] for row in rows).items() if count > 1)

    assert duplicates == []


def test_curated_foods_reconcile_late_928_dependencies() -> None:
    rows = _curated_food_rows()
    food_ids = {row["food_id"] for row in rows}

    assert len(food_ids) == len(PLANNED_LATE_928_INGREDIENT_FOOD_IDS)
    assert PROTECTED_RECOVERY_FOOD_IDS <= food_ids
    assert LATE_928_LATE_SOURCE_FOOD_IDS <= food_ids
    assert LATE_928_HISTORICAL_FOOD_IDS <= food_ids
    assert PLANNED_LATE_928_INGREDIENT_FOOD_IDS - food_ids == set()
    assert LATE_928_UNUSED_LATE_FOOD_IDS.isdisjoint(food_ids)


def test_curated_foods_reconciliation_uses_source_backed_rows() -> None:
    foods_by_id = {row["food_id"]: row for row in _curated_food_rows()}

    for food_id, (fdc_id, source_description) in EXPECTED_RECONCILED_FOOD_SOURCES.items():
        row = foods_by_id[food_id]
        nutrients = row["nutrients_per_100g"]

        assert row["fdc_id"] == fdc_id
        assert row["source_description"] == source_description
        assert nutrients["energy_kcal"] > 0
        assert nutrients["protein_g"] >= 0
        assert nutrients["fat_g"] >= 0
        assert nutrients["carbohydrate_g"] >= 0


def test_curated_foods_reconciliation_preserves_recovery_base_rows() -> None:
    base_rows = [
        row
        for row in _curated_food_rows()
        if row["food_id"] not in LATE_928_RECONCILED_FOOD_IDS
    ]
    payload = json.dumps(
        sorted(base_rows, key=lambda row: row["food_id"]),
        ensure_ascii=False,
        separators=(",", ":"),
        sort_keys=True,
    ).encode("utf-8")

    assert len(base_rows) == RECOVERY_BASE_FOOD_ROW_COUNT
    assert hashlib.sha256(payload).hexdigest() == RECOVERY_BASE_FOOD_ROWS_SHA256


def _curated_food_rows() -> list[dict[str, object]]:
    return json.loads((DATA_DIR / "curated_foods.json").read_text(encoding="utf-8"))
